# Generated by Django 4.2.2 on 2023-07-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('expediteur', models.EmailField(max_length=254)),
                ('destinataire', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
        ),
    ]
